import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Reusable branded PDF header/footer for all calcwise apps.
///
/// Use `pageTheme` for a one-liner that bakes in branded header + footer,
/// or call `header` / `footer` individually inside `pw.MultiPage`.
///
/// Premium hook: pass `customBrandName`, `customContactInfo`, and
/// `customLogo` to override defaults — wire this to a premium-only
/// "custom branding" feature where users attach their own logo + info.
class PdfBrandHelper {
  /// Brand color for headers (default: calcwise blue).
  static const PdfColor defaultBrand = PdfColor.fromInt(0xFF1976D2);

  /// Standard header with app name, generated date, optional custom logo (premium).
  static pw.Widget header({
    required String appName,
    required DateTime generatedAt,
    PdfColor brandColor = defaultBrand,
    String? customBrandName,
    String? customContactInfo,
    pw.MemoryImage? customLogo, // premium: user's own brand logo
  }) {
    final df =
        '${generatedAt.year}-${generatedAt.month.toString().padLeft(2, "0")}-${generatedAt.day.toString().padLeft(2, "0")}';
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: brandColor, width: 2)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Row(children: [
            if (customLogo != null) ...[
              pw.Image(customLogo, width: 32, height: 32),
              pw.SizedBox(width: 8),
            ],
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  customBrandName ?? appName,
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                    color: brandColor,
                  ),
                ),
                if (customContactInfo != null)
                  pw.Text(
                    customContactInfo,
                    style: const pw.TextStyle(
                        fontSize: 9, color: PdfColors.grey700),
                  ),
              ],
            ),
          ]),
          pw.Text(
            df,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
        ],
      ),
    );
  }

  /// Standard footer with page numbers and "Generated by [appName]".
  static pw.Widget footer(pw.Context ctx, String appName) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by $appName',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
          pw.Text(
            '${ctx.pageNumber} / ${ctx.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  /// Default page theme with branded header/footer baked in.
  static pw.PageTheme pageTheme({
    required String appName,
    PdfColor brandColor = defaultBrand,
    String? customBrandName,
    String? customContactInfo,
    pw.MemoryImage? customLogo,
  }) {
    final generatedAt = DateTime.now();
    return pw.PageTheme(
      pageFormat: PdfPageFormat.a4.copyWith(
        marginBottom: 60,
        marginTop: 70,
        marginLeft: 40,
        marginRight: 40,
      ),
      buildBackground: (ctx) => pw.FullPage(
        ignoreMargins: false,
        child: pw.Stack(children: [
          pw.Positioned(
            top: 20,
            left: 40,
            right: 40,
            child: header(
              appName: appName,
              generatedAt: generatedAt,
              brandColor: brandColor,
              customBrandName: customBrandName,
              customContactInfo: customContactInfo,
              customLogo: customLogo,
            ),
          ),
          pw.Positioned(
            bottom: 20,
            left: 40,
            right: 40,
            child: footer(ctx, appName),
          ),
        ]),
      ),
    );
  }
}
